//
//  ImageDetailPresenter.swift
//  iBooChallenge
//
//  Created by Jordi Serra i Font on 19/2/17.
//  Copyright (c) 2017 kudai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ImageDetailPresenterInput
{
  func presentSomething(response: ImageDetail.Something.Response)
}

protocol ImageDetailPresenterOutput: class
{
  func displaySomething(viewModel: ImageDetail.Something.ViewModel)
}

class ImageDetailPresenter: ImageDetailPresenterInput
{
  weak var output: ImageDetailPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ImageDetail.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ImageDetail.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
