//
//  ImageDetailInteractor.swift
//  iBooChallenge
//
//  Created by Jordi Serra i Font on 19/2/17.
//  Copyright (c) 2017 kudai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ImageDetailInteractorInput
{
  func doSomething(request: ImageDetail.Something.Request)
}

protocol ImageDetailInteractorOutput
{
  func presentSomething(response: ImageDetail.Something.Response)
}

class ImageDetailInteractor: ImageDetailInteractorInput
{
  var output: ImageDetailInteractorOutput!
  var worker: ImageDetailWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: ImageDetail.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ImageDetailWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ImageDetail.Something.Response()
    output.presentSomething(response: response)
  }
}
