//
//  ImageDetailConfigurator.swift
//  iBooChallenge
//
//  Created by Jordi Serra i Font on 19/2/17.
//  Copyright (c) 2017 kudai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ImageDetailViewController: ImageDetailPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ImageDetailInteractor: ImageDetailViewControllerOutput
{
}

extension ImageDetailPresenter: ImageDetailInteractorOutput
{
}

class ImageDetailConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ImageDetailConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ImageDetailViewController)
  {
    let router = ImageDetailRouter()
    router.viewController = viewController
    
    let presenter = ImageDetailPresenter()
    presenter.output = viewController
    
    let interactor = ImageDetailInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
