//
//  ImagesListConfigurator.swift
//  iBooChallenge
//
//  Created by Jordi Serra i Font on 19/2/17.
//  Copyright (c) 2017 kudai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ImagesListViewController: ImagesListPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension ImagesListInteractor: ImagesListViewControllerOutput {
}

extension ImagesListPresenter: ImagesListInteractorOutput {
}

class ImagesListConfigurator {
    // MARK: - Object lifecycle
    
    static let sharedInstance = ImagesListConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(viewController: ImagesListViewController) {
        let router = ImagesListRouter()
        router.viewController = viewController
        
        let presenter = ImagesListPresenter()
        presenter.output = viewController
        
        let interactor = ImagesListInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
