//
//  ImagesListInteractor.swift
//  iBooChallenge
//
//  Created by Jordi Serra i Font on 19/2/17.
//  Copyright (c) 2017 kudai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ImagesListInteractorInput {
    func searchImages(request: ImagesList.Search.Request)
}

protocol ImagesListInteractorOutput {
    func presentSearch(response: ImagesList.Search.Response)
}

class ImagesListInteractor: ImagesListInteractorInput {
    var output: ImagesListInteractorOutput!
    
    // MARK: - Business logic
    
    func searchImages(request: ImagesList.Search.Request) {
        
        let params: [String: Any] = [
            "phrase": request.searchTerm,
            "page": request.currentPage,
            "page_size": request.numberOfItems
        ]
        
        let searchTask = GettyFetcher.instance.retrieveGetty(withAPICall: .search, params: params)
        
        searchTask.upon(DispatchQueue.main) { (result) in
            let response = ImagesList.Search.Response(taskResult: result)
            self.output.presentSearch(response: response)
        }
    }
}
