//
//  ImagesListViewController.swift
//  iBooChallenge
//
//  Created by Jordi Serra i Font on 19/2/17.
//  Copyright (c) 2017 kudai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ImagesListViewControllerInput {
    func displayImages(viewModel: ImagesList.Search.ViewModel)
    func displayError(_ viewModel: ImagesList.Search.ErrorViewModel)
}

protocol ImagesListViewControllerOutput {
    func searchImages(request: ImagesList.Search.Request)
}

class ImagesListViewController: UIViewController, ImagesListViewControllerInput {
    var output: ImagesListViewControllerOutput!
    var router: ImagesListRouter!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ImagesListConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        searchImagesOnLoad()
    }
    
    // MARK: - Event handling
    
    func searchImagesOnLoad() {
        // NOTE: Ask the Interactor to do some work
        
        let request = ImagesList.Search.Request(searchTerm: "Barcelona")
        output.searchImages(request: request)
    }
    
    // MARK: - Display logic
    
    func displayImages(viewModel: ImagesList.Search.ViewModel) {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
    
    func displayError(_ viewModel: ImagesList.Search.ErrorViewModel) {
        
    }
}
